name       : qt6-lottie
version    : 6.3.0
release    : 3
source     :
    - https://download.qt.io/official_releases/qt/6.3/6.3.0/submodules/qtlottie-everywhere-src-6.3.0.tar.xz : 39db570bbba5b527a1eb6a5774bed47398ace2f7217bbf45b1194ada6cf97deb
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt6 Lottie Animation module
description: |
    Qt Lottie Animation provides a QML API for rendering graphics and animations that are exported in JSON format.
builddeps  :
    - pkgconfig(Qt6Qml)
rundeps    :
    - devel :
        - qt6-declarative-devel
setup      : |
    %patch -p1 < $pkgfiles/implement-missing-null-layer.patch
    %patch -p1 < $pkgfiles/implement-missing-merge-shape.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
