name       : qt6-lottie
version    : 6.5.1
release    : 4
source     :
    - https://download.qt.io/official_releases/qt/6.5/6.5.1/submodules/qtlottie-everywhere-src-6.5.1.tar.xz : 10b8f8107b75314703a4d0e0f60778c30c8f41a339622bc8166eec284ac26b81
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt6 Lottie Animation module
description: |
    Qt Lottie Animation provides a QML API for rendering graphics and animations that are exported in JSON format.
builddeps  :
    - pkgconfig(Qt6Qml)
rundeps    :
    - devel :
        - qt6-declarative-devel
setup      : |
    %patch -p1 < $pkgfiles/implement-missing-null-layer.patch
    %patch -p1 < $pkgfiles/implement-missing-merge-shape.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
