name       : qt6-lottie
version    : 6.2.2
release    : 2
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.2/submodules/qtlottie-everywhere-src-6.2.2.tar.xz : 9c2ac91b9f5dc860d211ed9f3c1e3965dbb4665ace4af735e96b6328990fd74f
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt6 Lottie Animation module
description: |
    Qt Lottie Animation provides a QML API for rendering graphics and animations that are exported in JSON format.
builddeps  :
    - pkgconfig(Qt6Qml)
rundeps    :
    - devel :
        - qt6-declarative-devel
setup      : |
    %patch -p1 < $pkgfiles/implement-missing-null-layer.patch
    %patch -p1 < $pkgfiles/implement-missing-merge-shape.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
